In [3]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [4]:
import pandas as pd
import numpy as np

In [6]:
dfNorm=pd.read_csv('/content/drive/MyDrive/ml/sleepNonorm.csv')
dfNoNorm=pd.read_csv('/content/drive/MyDrive/ml/sleepNorm.csv')
dfNorm

,Unnamed: 0,pid,date,f_slp:fitbit_sleep_summary_rapids_avgefficiencymain:allday,f_slp:fitbit_sleep_summary_rapids_avgefficiencymain_norm:allday,f_slp:fitbit_sleep_summary_rapids_sumdurationasleepmain_norm:allday,f_slp:fitbit_sleep_summary_rapids_sumdurationasleepmain:allday,f_blue:phone_bluetooth_doryab_uniquedevicesall:allday,f_blue:phone_bluetooth_doryab_uniquedevicesall:afternoon,f_blue:phone_bluetooth_doryab_uniquedevicesall:evening,...,f_steps:fitbit_steps_intraday_rapids_sumsteps:evening,f_steps:fitbit_steps_intraday_rapids_countepisodeactivebout:evening,f_steps:fitbit_steps_intraday_rapids_sumdurationactivebout:evening,f_steps:fitbit_steps_intraday_rapids_sumsteps:morning,f_steps:fitbit_steps_intraday_rapids_countepisodeactivebout:morning,f_steps:fitbit_steps_intraday_rapids_sumdurationactivebout:morning,f_steps:fitbit_steps_intraday_rapids_sumsteps:night,f_steps:fitbit_steps_intraday_rapids_countepisodeactivebout:night,f_steps:fitbit_steps_intraday_rapids_sumdurationactivebout:night,date_
0,0,INS-W_001,2018-04-03,95.0,0.141844,-0.294479,347.0,NaN,NaN,NaN,...,4203.0,40.0,99.0,19.0,1.0,1.0,4392.0,24.0,87.0,2018-04-03
1,1,INS-W_001,2018-04-04,91.0,-0.425532,-0.147239,395.0,NaN,NaN,NaN,...,2592.0,20.0,57.0,4804.0,7.0,61.0,1663.0,29.0,47.0,2018-04-04
2,2,INS-W_001,2018-04-05,95.0,0.141844,0.392638,571.0,NaN,NaN,NaN,...,6071.0,42.0,125.0,3137.0,11.0,49.0,1263.0,16.0,34.0,2018-04-05
3,3,INS-W_001,2018-04-06,96.0,0.283688,-0.273006,354.0,NaN,NaN,NaN,...,4734.0,25.0,95.0,4.0,NaN,NaN,1241.0,15.0,35.0,2018-04-06
4,4,INS-W_001,2018-04-07,95.0,0.141844,0.472393,597.0,NaN,NaN,NaN,...,7569.0,25.0,129.0,1406.0,17.0,39.0,1823.0,22.0,56.0,2018-04-07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11465,14237,INS-W_208,2018-06-11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-06-11
11466,14238,INS-W_208,2018-06-12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-06-12
11467,14239,INS-W_208,2018-06-13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-06-13
11468,14240,INS-W_208,2018-06-14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-06-14
11469,14241,INS-W_208,2018-06-15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-06-15

In [7]:
dfNoNorm

,Unnamed: 0,pid,date,f_slp:fitbit_sleep_summary_rapids_avgefficiencymain:allday,f_slp:fitbit_sleep_summary_rapids_avgefficiencymain_norm:allday,f_slp:fitbit_sleep_summary_rapids_sumdurationasleepmain_norm:allday,f_slp:fitbit_sleep_summary_rapids_sumdurationasleepmain:allday,f_blue:phone_bluetooth_doryab_uniquedevicesall_norm:allday,f_blue:phone_bluetooth_doryab_uniquedevicesall_norm:afternoon,f_blue:phone_bluetooth_doryab_uniquedevicesall_norm:evening,...,f_steps:fitbit_steps_intraday_rapids_sumsteps_norm:evening,f_steps:fitbit_steps_intraday_rapids_countepisodeactivebout_norm:evening,f_steps:fitbit_steps_intraday_rapids_sumdurationactivebout_norm:evening,f_steps:fitbit_steps_intraday_rapids_sumsteps_norm:morning,f_steps:fitbit_steps_intraday_rapids_countepisodeactivebout_norm:morning,f_steps:fitbit_steps_intraday_rapids_sumdurationactivebout_norm:morning,f_steps:fitbit_steps_intraday_rapids_sumsteps_norm:night,f_steps:fitbit_steps_intraday_rapids_countepisodeactivebout_norm:night,f_steps:fitbit_steps_intraday_rapids_sumdurationactivebout_norm:night,date_
0,0,INS-W_001,2018-04-03,95.0,0.141844,-0.294479,347.0,NaN,NaN,NaN,...,0.019403,0.363636,0.019737,-0.203456,-0.310345,-0.315789,0.938046,0.607143,0.818505,2018-04-03
1,1,INS-W_001,2018-04-04,91.0,-0.425532,-0.147239,395.0,NaN,NaN,NaN,...,-0.133076,-0.242424,-0.256579,0.713246,-0.103448,0.210526,0.275539,0.785714,0.344009,2018-04-04
2,2,INS-W_001,2018-04-05,95.0,0.141844,0.392638,571.0,NaN,NaN,NaN,...,0.196206,0.424242,0.190789,0.393885,0.034483,0.105263,0.178433,0.321429,0.189798,2018-04-05
3,3,INS-W_001,2018-04-06,96.0,0.283688,-0.273006,354.0,NaN,NaN,NaN,...,0.069661,-0.090909,-0.006579,-0.206330,NaN,NaN,0.173092,0.285714,0.201661,2018-04-06
4,4,INS-W_001,2018-04-07,95.0,0.141844,0.472393,597.0,NaN,NaN,NaN,...,0.337990,-0.090909,0.217105,0.062263,0.241379,0.017544,0.314381,0.535714,0.450771,2018-04-07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11465,14237,INS-W_208,2018-06-11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-06-11
11466,14238,INS-W_208,2018-06-12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-06-12
11467,14239,INS-W_208,2018-06-13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-06-13
11468,14240,INS-W_208,2018-06-14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-06-14
11469,14241,INS-W_208,2018-06-15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-06-15

In [13]:
display(dfNorm.isna().sum())

Unnamed: 0                                                                      0
pid                                                                             0
date                                                                            0
f_slp:fitbit_sleep_summary_rapids_avgefficiencymain:allday                   4214
f_slp:fitbit_sleep_summary_rapids_avgefficiencymain_norm:allday              4214
f_slp:fitbit_sleep_summary_rapids_sumdurationasleepmain_norm:allday          4134
f_slp:fitbit_sleep_summary_rapids_sumdurationasleepmain:allday               4134
f_blue:phone_bluetooth_doryab_uniquedevicesall:allday                        1892
f_blue:phone_bluetooth_doryab_uniquedevicesall:afternoon                     2769
f_blue:phone_bluetooth_doryab_uniquedevicesall:evening                       3508
f_blue:phone_bluetooth_doryab_uniquedevicesall:morning                       3909
f_blue:phone_bluetooth_doryab_uniquedevicesall:night                         6069
f_call:phone_calls_rapids_missed_count:afternoon                             8685
f_call:phone_calls_rapids_incoming_count:afternoon                           8685
f_call:phone_calls_rapids_incoming_sumduration:afternoon                    10002
f_call:phone_calls_rapids_outgoing_count:afternoon                           8685
f_call:phone_calls_rapids_outgoing_sumduration:afternoon                     9558
f_call:phone_calls_rapids_missed_count:allday                                7305
f_call:phone_calls_rapids_incoming_count:allday                              7305
f_call:phone_calls_rapids_incoming_sumduration:allday                        8904
f_call:phone_calls_rapids_outgoing_count:allday                              7305
f_call:phone_calls_rapids_outgoing_sumduration:allday                        8245
f_call:phone_calls_rapids_missed_count:evening                               8973
f_call:phone_calls_rapids_incoming_count:evening                             8973
f_call:phone_calls_rapids_incoming_sumduration:evening                      10110
f_call:phone_calls_rapids_outgoing_count:evening                             8973
f_call:phone_calls_rapids_outgoing_sumduration:evening                       9660
f_call:phone_calls_rapids_missed_count:morning                              10004
f_call:phone_calls_rapids_incoming_count:morning                            10004
f_call:phone_calls_rapids_incoming_sumduration:morning                      10841
f_call:phone_calls_rapids_outgoing_count:morning                            10004
f_call:phone_calls_rapids_outgoing_sumduration:morning                      10624
f_call:phone_calls_rapids_missed_count:night                                11065
f_call:phone_calls_rapids_incoming_count:night                              11065
f_call:phone_calls_rapids_incoming_sumduration:night                        11282
f_call:phone_calls_rapids_outgoing_count:night                              11065
f_call:phone_calls_rapids_outgoing_sumduration:night                        11198
f_loc:phone_locations_barnett_circdnrtn:afternoon                           11470
f_loc:phone_locations_barnett_hometime:afternoon                            11470
f_loc:phone_locations_barnett_rog:afternoon                                 11470
f_loc:phone_locations_barnett_siglocsvisited:afternoon                      11470
f_loc:phone_locations_barnett_wkenddayrtn:afternoon                         11470
f_loc:phone_locations_doryab_movingtostaticratio:afternoon                   1675
f_loc:phone_locations_doryab_timeathome:afternoon                            1675
f_loc:phone_locations_doryab_totaldistance:afternoon                         1675
f_loc:phone_locations_locmap_duration_in_locmap_study:afternoon              1675
f_loc:phone_locations_locmap_duration_in_locmap_exercise:afternoon           1675
f_loc:phone_locations_locmap_duration_in_locmap_greens:afternoon             1675
f_loc:phone_locations_barnett_circdnrtn:allday                               1419
f_loc:phone_locations_barnett_hometime:allday                                1418
f_loc:phone_locations_barnett_rog:allday                                     1418
f_loc:phone_locations_barnett_siglocsvisited:allday                          1418
f_loc:phone_locations_barnett_wkenddayrtn:allday                             1419
f_loc:phone_locations_doryab_movingtostaticratio:allday                      1406
f_loc:phone_locations_doryab_timeathome:allday                               1406
f_loc:phone_locations_doryab_totaldistance:allday                            1406
f_loc:phone_locations_locmap_duration_in_locmap_study:allday                 1406
f_loc:phone_locations_locmap_duration_in_locmap_exercise:allday              1406
f_loc:phone_locations_locmap_duration_in_locmap_greens:allday                1406
f_loc:phone_locations_barnett_circdnrtn:evening                             11470
f_loc:phone_locations_barnett_hometime:evening                              11470
f_loc:phone_locations_barnett_rog:evening                                   11470
f_loc:phone_locations_barnett_siglocsvisited:evening                        11470
f_loc:phone_locations_barnett_wkenddayrtn:evening                           11470
f_loc:phone_locations_doryab_movingtostaticratio:evening                     1796
f_loc:phone_locations_doryab_timeathome:evening                              1796
f_loc:phone_locations_doryab_totaldistance:evening                           1796
f_loc:phone_locations_locmap_duration_in_locmap_study:evening                1796
f_loc:phone_locations_locmap_duration_in_locmap_exercise:evening             1796
f_loc:phone_locations_locmap_duration_in_locmap_greens:evening               1796
f_loc:phone_locations_barnett_circdnrtn:morning                             11470
f_loc:phone_locations_barnett_hometime:morning                              11470
f_loc:phone_locations_barnett_rog:morning                                   11470
f_loc:phone_locations_barnett_siglocsvisited:morning                        11470
f_loc:phone_locations_barnett_wkenddayrtn:morning                           11470
f_loc:phone_locations_doryab_movingtostaticratio:morning                     1930
f_loc:phone_locations_doryab_timeathome:morning                              1930
f_loc:phone_locations_doryab_totaldistance:morning                           1929
f_loc:phone_locations_locmap_duration_in_locmap_study:morning                1929
f_loc:phone_locations_locmap_duration_in_locmap_exercise:morning             1929
f_loc:phone_locations_locmap_duration_in_locmap_greens:morning               1929
f_loc:phone_locations_barnett_circdnrtn:night                               11470
f_loc:phone_locations_barnett_hometime:night                                11470
f_loc:phone_locations_barnett_rog:night                                     11470
f_loc:phone_locations_barnett_siglocsvisited:night                          11470
f_loc:phone_locations_barnett_wkenddayrtn:night                             11470
f_loc:phone_locations_doryab_movingtostaticratio:night                       2431
f_loc:phone_locations_doryab_timeathome:night                                2431
f_loc:phone_locations_doryab_totaldistance:night                             2431
f_loc:phone_locations_locmap_duration_in_locmap_study:night                  2431
f_loc:phone_locations_locmap_duration_in_locmap_exercise:night               2431
f_loc:phone_locations_locmap_duration_in_locmap_greens:night                 2431
f_screen:phone_screen_rapids_countepisodeunlock:afternoon                    1631
f_screen:phone_screen_rapids_sumdurationunlock:afternoon                     1631
f_screen:phone_screen_rapids_sumdurationunlock_locmap_exercise:afternoon     9931
f_screen:phone_screen_rapids_sumdurationunlock_locmap_greens:afternoon       6427
f_screen:phone_screen_rapids_sumdurationunlock_locmap_living:afternoon       5823
f_screen:phone_screen_rapids_sumdurationunlock_locmap_study:afternoon        6826
f_screen:phone_screen_rapids_sumdurationunlock_locmap_home:afternoon         4101
f_screen:phone_screen_rapids_countepisodeunlock:allday                       1439
f_screen:phone_screen_rapids_sumdurationunlock:allday                        1439
f_screen:phone_screen_rapids_sumdurationunlock_locmap_exercise:allday        8782
f_screen:phone_screen_rapids_sumdurationunlock_locmap_greens:allday          4778
f_screen:phone_screen_rapids_sumdurationunlock_locmap_living:allday          4075
f_screen:phone_screen_rapids_sumdurationunlock_locmap_study:allday           5349
f_screen:phone_screen_rapids_sumdurationunlock_locmap_home:allday            2328
f_screen:phone_screen_rapids_countepisodeunlock:evening                      1770
f_screen:phone_screen_rapids_sumdurationunlock:evening                       1770
f_screen:phone_screen_rapids_sumdurationunlock_locmap_exercise:evening      10233
f_screen:phone_screen_rapids_sumdurationunlock_locmap_greens:evening         8711
f_screen:phone_screen_rapids_sumdurationunlock_locmap_living:evening         5507
f_screen:phone_screen_rapids_sumdurationunlock_locmap_study:evening          9422
f_screen:phone_screen_rapids_sumdurationunlock_locmap_home:evening           3550
f_screen:phone_screen_rapids_countepisodeunlock:morning                      2096
f_screen:phone_screen_rapids_sumdurationunlock:morning                       2096
f_screen:phone_screen_rapids_sumdurationunlock_locmap_exercise:morning      10798
f_screen:phone_screen_rapids_sumdurationunlock_locmap_greens:morning         7876
f_screen:phone_screen_rapids_sumdurationunlock_locmap_living:morning         6254
f_screen:phone_screen_rapids_sumdurationunlock_locmap_study:morning          8303
f_screen:phone_screen_rapids_sumdurationunlock_locmap_home:morning           4154
f_screen:phone_screen_rapids_countepisodeunlock:night                        3675
f_screen:phone_screen_rapids_sumdurationunlock:night                         3675
f_screen:phone_screen_rapids_sumdurationunlock_locmap_exercise:night        11359
f_screen:phone_screen_rapids_sumdurationunlock_locmap_greens:night          10770
f_screen:phone_screen_rapids_sumdurationunlock_locmap_living:night           7309
f_screen:phone_screen_rapids_sumdurationunlock_locmap_study:night           11082
f_screen:phone_screen_rapids_sumdurationunlock_locmap_home:night             5278
f_steps:fitbit_steps_intraday_rapids_sumsteps:afternoon                      3397
f_steps:fitbit_steps_intraday_rapids_countepisodeactivebout:afternoon        3703
f_steps:fitbit_steps_intraday_rapids_sumdurationactivebout:afternoon         3703
f_steps:fitbit_steps_intraday_rapids_sumsteps:allday                         3397
f_steps:fitbit_steps_intraday_rapids_countepisodeactivebout:allday           3397
f_steps:fitbit_steps_intraday_rapids_sumdurationactivebout:allday            3397
f_steps:fitbit_steps_intraday_rapids_sumsteps:evening                        3397
f_steps:fitbit_steps_intraday_rapids_countepisodeactivebout:evening          3796
f_steps:fitbit_steps_intraday_rapids_sumdurationactivebout:evening           3796
f_steps:fitbit_steps_intraday_rapids_sumsteps:morning                        3397
f_steps:fitbit_steps_intraday_rapids_countepisodeactivebout:morning          4074
f_steps:fitbit_steps_intraday_rapids_sumdurationactivebout:morning           4074
f_steps:fitbit_steps_intraday_rapids_sumsteps:night                          3397
f_steps:fitbit_steps_intraday_rapids_countepisodeactivebout:night            5323
f_steps:fitbit_steps_intraday_rapids_sumdurationactivebout:night             5323
date_                                                                           0
dtype: int64

In [ ]:
11470*143

In [19]:
na_counts = dfNorm.isna().sum()
columns_to_drop = na_counts[na_counts > 11000].index.tolist()
# dfNorm_dropped = dfNorm.drop(columns=columns_to_drop)
# display(dfNorm_dropped.isna().sum())
columns_to_drop

['f_call:phone_calls_rapids_missed_count:night',
 'f_call:phone_calls_rapids_incoming_count:night',
 'f_call:phone_calls_rapids_incoming_sumduration:night',
 'f_call:phone_calls_rapids_outgoing_count:night',
 'f_call:phone_calls_rapids_outgoing_sumduration:night',
 'f_loc:phone_locations_barnett_circdnrtn:afternoon',
 'f_loc:phone_locations_barnett_hometime:afternoon',
 'f_loc:phone_locations_barnett_rog:afternoon',
 'f_loc:phone_locations_barnett_siglocsvisited:afternoon',
 'f_loc:phone_locations_barnett_wkenddayrtn:afternoon',
 'f_loc:phone_locations_barnett_circdnrtn:evening',
 'f_loc:phone_locations_barnett_hometime:evening',
 'f_loc:phone_locations_barnett_rog:evening',
 'f_loc:phone_locations_barnett_siglocsvisited:evening',
 'f_loc:phone_locations_barnett_wkenddayrtn:evening',
 'f_loc:phone_locations_barnett_circdnrtn:morning',
 'f_loc:phone_locations_barnett_hometime:morning',
 'f_loc:phone_locations_barnett_rog:morning',
 'f_loc:phone_locations_barnett_siglocsvisited:morning',
 'f_loc:phone_locations_barnett_wkenddayrtn:morning',
 'f_loc:phone_locations_barnett_circdnrtn:night',
 'f_loc:phone_locations_barnett_hometime:night',
 'f_loc:phone_locations_barnett_rog:night',
 'f_loc:phone_locations_barnett_siglocsvisited:night',
 'f_loc:phone_locations_barnett_wkenddayrtn:night',
 'f_screen:phone_screen_rapids_sumdurationunlock_locmap_exercise:night',
 'f_screen:phone_screen_rapids_sumdurationunlock_locmap_study:night']

In [22]:
na_counts2 = dfNoNorm.isna().sum()
columns_to_drop2 = na_counts2[na_counts2 > 11000].index.tolist()
# dfNoNorm_dropped = dfNoNorm.drop(columns=columns_to_drop2)
# display(dfNoNorm_dropped.isna().sum())
columns_to_drop2

['f_call:phone_calls_rapids_missed_count_norm:night',
 'f_call:phone_calls_rapids_incoming_count_norm:night',
 'f_call:phone_calls_rapids_incoming_sumduration_norm:night',
 'f_call:phone_calls_rapids_outgoing_count_norm:night',
 'f_call:phone_calls_rapids_outgoing_sumduration_norm:night',
 'f_loc:phone_locations_barnett_circdnrtn_norm:afternoon',
 'f_loc:phone_locations_barnett_hometime_norm:afternoon',
 'f_loc:phone_locations_barnett_rog_norm:afternoon',
 'f_loc:phone_locations_barnett_siglocsvisited_norm:afternoon',
 'f_loc:phone_locations_barnett_wkenddayrtn_norm:afternoon',
 'f_loc:phone_locations_barnett_circdnrtn_norm:evening',
 'f_loc:phone_locations_barnett_hometime_norm:evening',
 'f_loc:phone_locations_barnett_rog_norm:evening',
 'f_loc:phone_locations_barnett_siglocsvisited_norm:evening',
 'f_loc:phone_locations_barnett_wkenddayrtn_norm:evening',
 'f_loc:phone_locations_barnett_circdnrtn_norm:morning',
 'f_loc:phone_locations_barnett_hometime_norm:morning',
 'f_loc:phone_locations_barnett_rog_norm:morning',
 'f_loc:phone_locations_barnett_siglocsvisited_norm:morning',
 'f_loc:phone_locations_barnett_wkenddayrtn_norm:morning',
 'f_loc:phone_locations_barnett_circdnrtn_norm:night',
 'f_loc:phone_locations_barnett_hometime_norm:night',
 'f_loc:phone_locations_barnett_rog_norm:night',
 'f_loc:phone_locations_barnett_siglocsvisited_norm:night',
 'f_loc:phone_locations_barnett_wkenddayrtn_norm:night',
 'f_screen:phone_screen_rapids_sumdurationunlock_locmap_exercise_norm:night',
 'f_screen:phone_screen_rapids_sumdurationunlock_locmap_study_norm:night']

In [17]:
dfNorm.shape

(11470, 116)